ethereum:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: "{{ env_var('BG_METHOD') }}"
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: "{{ env_var('BQ_DATASET') }}"
      keyfile: "{{ env_var('BQ_KEYFILE') }}"
      threads: 2
      client_session_keep_alive: False